### ISSUE TITLE
Could not access processing script via WPS

### ISSUE THREAD

**Issue by pkthogit** [3liz/py-qgis-wps#12]
Hi Team,

As I could manage to setup WPS service on Linux machine and able to run it from source code, however, I could send request with simplevalue processing script. When I access http://localhost:8080/store/pyqgiswps_Main/simplevalue?service=WPS, it shows below error message and console shows the python file is expected to be available in output folder. Not sure whether I did anything wrong or is it a bug in the code (as I suspect).

<ows:Exception exceptionCode="NoApplicableCode" locator="">
<ows:ExceptionText>Resource not found</ows:ExceptionText>
</ows:Exception>

2021-04-15 11:21:24,933 [1563]  ERROR   File '/home/adminuser/py-qgis-wps-master/__outputdata___/pyqgiswps_Main/simplevalue' not found
2021-04-15 11:21:24,933 [1563]  ERROR   Exception: code: 404, description: Resource not found, locator:
2021-04-15 11:21:24,933 [1563]  DEBUG   Request failed wint message: Resource not found HTTP 404: Not Found
2021-04-15 11:21:24,933 [1563]  DEBUG   Serializing XML response

As I am pretty new to this py-qgis-wps, wondering whether we have,

1. any dashboard url to see the status of jobs in webpage, (I see the webui code and html but could not get the url to access)
2. any request response sample to send geometry geojson in request and input processing parameter for the same. 

It would be really helpful to me if someone can help me in this regards.

-Prem

**Comment by dmarteau** [comment]
The error seems pretty clear for me:
```
'/home/adminuser/py-qgis-wps-master/outputdata_/pyqgiswps_Main/simplevalue' not found
```
Check that file exists on your host.

But I wonder how did you come out with this uri: `/store/pyqgiswps_Main/simplevalue?service=WPS` ? What are you trying to do ?

The `store` API has a very specific purpose and cannot be used for accessing your server scripts files.

**Comment by dmarteau** [comment]
> any dashboard url to see the status of jobs in webpage, (I see the webui code and html but could not get the url to access)

Try `http://localhost:8080/ui/`

> any request response sample to send geometry geojson in request and input processing parameter for the same.

Py-qgis-wps implement OGC WPS  standard to describe and pass parameters to process and do marshalling  from and to processinc parameters.  From a Qgis processing users point of view  this is handled transparently, and your client is assumed to  "talk" the WPS standard.

**Comment by pkthogit** [comment]
Hi David, Thank you very much for your reply. 

i have tried http://<hostname>:8080/ui to access the dashboard page and it works fine to me, thanks for the help.

I could not find the request url format to test the **simplevalue** processing script working. Could you please help me with the published processing script url. Thank you.

2021-04-15 14:26:33,099 [1405]  DEBUG   Loading processing algorithms from provider 'pyqgiswps_Main'
2021-04-15 14:26:33,101 [1405]  INFO    Published processes:
 * pyqgiswps_Main:simplevalue
2021-04-15 14:26:33,120 [1405]  INFO    Starting supervisor
2021-04-15 14:26:33,121 [1405]  INFO    WPS Server ready


-Prem

**Comment by dmarteau** [comment]
>  Could you please help me with the published processing script url. 

You  can eventually test with a `GetCapabilities` request:  `http://localhost:8080/ows/?SERVICE=WPS&Request=GetCapabilities`

From this please refer to the documentation of the WPS standard: https://www.ogc.org/standards/wps
