### ISSUE TITLE
how can i send geojson files as input to a process exist in the server (in PSOT and GET)

### ISSUE THREAD

**Issue by ayoubTig** [3liz/py-qgis-wps#13]
Hello, 
how can i send geojson files to server in order to run it ?
how can i display layers of qgis projects in browser  using MAP parameter ? 
I am executing this request http://127.0.0.7:8040/?MAP=/home/ayuob19971/Bureau/PFE/v2/py-qgis-wps-1.6.0/tests/unittests/data/france_parts.qgs&service=WMS&request=GetCapabilities
The results is :

author | "3Liz"
author_url | "http://3liz.com"
config |  
DEFAULT | {}
logging |  
level | "DEBUG"
logstorage:redis |  
dbnum | "0"
host | "localhost"
port | "6379"
prefix | "pyqgiswps"
metadata:main |  
contact_address | "Mailing Address"
contact_email | "Email Address"
contact_name | "Lastname, Firstname"
contact_role | "pointOfContact"
contact_url | "Contact URL"
identification_abstract | "Py-Qgis-WPS is an implementation of the Web Processing Service standard from the Open Geospatial Consortium. Py-Qgis-WPS is written in Python."
identification_accessconstraints | "NONE"
identification_fees | "NONE"
identification_keywords | "Py-Qgis-WPS,WPS,OGC,QGIS,processing"
identification_keywords_type | "theme"
identification_title | "Py-Qgis-WPS Processing Service"
provider_name | "Organization Name"
provider_url | "https://github.com/3liz/py-qgis-wps"
processing |  
accesspolicy | "/accesspolicy.yml"
default_module_path | "/usr/share/qgis_wps/processing"
exposed_providers | "script,model"
providers_module_path | ""
projects.cache |  
rootdir | ""
size | "10"
strict_check | "yes"
projects.schemes | {}
qgis.projects |  
wmsurl | "${server:wms_service_url}"
qgis.settings | {}
qgis.settings.folders |  
Processing/Configuration/MODELS_FOLDER | "/models"
Processing/Configuration/SCRIPTS_FOLDERS | "/scripts"
server |  
CACHE_ROOTDIR | "/home/ayuob19971/Bureau/PFE/v2/py-qgis-wps-1.6.0/tests/unittests/data"
PROCESSING_EXPOSED_PROVIDERS | "TestCopyLayer,TestAlgorithmProvider"
SERVER_PARALLELPROCESSES | "3"
SERVER_WORKDIR | "/home/ayuob19971/Bureau/PFE/v2/py-qgis-wps-1.6.0"
cleanup_interval | "600"
download_ttl | "30"
enable_filters | "yes"
encoding | "utf-8"
host_proxy | ""
interfaces | "127.0.0.7"
language | "en-US"
maxbuffersize | "1m"
maxinputsize | "100m"
maxqueuesize | "100"
outputfile_as_reference | "yes"
parallelprocesses | "1"
port | "8040"
processlifecycle | "1"
providers_module_path | "/home/ayuob19971/Bureau/PFE/v2/py-qgis-wps-1.6.0/tests/unittests/algorithms"
response_expiration | "86400"
response_timeout | "1800"
status_url | "{host_url}ows/?service=WPS&request=GetResults&uuid={uuid}"
store_url | "{host_url}store/{uuid}/{file}?service=WPS"
sys_config_path | "/usr/share/qgis_wps"
url | "{host_url}"
wms_response_uri | "${wms_service_url}?MAP={map_url}&service=WMS&request=GetCapabilities"
wms_service_url | "${wps.request:host_url}"
workdir | "/tmp"
wps_result_map_uri | "wps-results:"
wps.request | {}
qgis_version | "31802 (Zürich)"
styles | {}
tornado_ver | "6.1"
version | "n/a"

**Comment by dmarteau** [comment]
It totally depends on how you have defined your input in the Processing side: usually one define a [`QgsProcessingParameterFile`](https://qgis.org/api/classQgsProcessingParameterFile.html) as input of your processing algorithm. This parameter will be translated as a WPS complex input with a mime type. 

There is mainly two may to get complex data in and out WPS processes: passing content in the body or by reference, in the latter case the input/value is an uri telling the where to get or to serve the result file.

How output file is sent to the client is controled by the [`SERVER_OUTPUTFILE_AS_REFERENCE`](https://py-qgis-wps.readthedocs.io/en/latest/configuration.html#server-outputfile-as-reference) configuration oHption.

How input file is sent to the server is controled by the format of the input of the WPS `Execute` request.

**Comment by dmarteau** [comment]
> how can i display layers of qgis projects in browser using MAP parameter ?

You need a WMS/WFS server (like [py-qgis-server](https://github.com/3liz/py-qgis-server))
