### ISSUE TITLE
The output project has no CRS

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-wps#17]
In old QGIS, before 3.16, projects have a default CRS. With QGIS 3.16 and upper, projects can have no CRS. For QGIS Server, the project has to have a CRS, but the project build by WPS has no CRS.

To fix it, py-qgis-wps can set the project CRS with the project used to perform the processes.

**Comment by chrimohr** [comment]
I ran into the same issue yesterday and had a short look at it.
Do you already have an idea where to fix this problem?

Would it be possible to add a default CRS (like EPSG:4326) in the `config.py` file under Qgis project settings?
https://github.com/3liz/py-qgis-wps/blob/edd29750a12050aea86290a2c2f54dbff1ddf88f/pyqgiswps/config.py#L165-L178

I'm relatively new to this whole project so there might be things I've missed or just don't understand jet.

**Comment by dmarteau** [comment]
> Would it be possible to add a default CRS (like EPSG:4326) in the config.py file under Qgis project settings?

There is no need for that: the project created must have the same CRS as the source project

**Comment by dmarteau** [comment]
Fixed in e6226ccac4ed4fb3b9497418a214fbb64b8ee5cf
