### ISSUE TITLE
Erreur 'Unknown process' à l'exécution d'une requête Execute

### ISSUE THREAD

**Issue by mgaudin** [3liz/py-qgis-wps#20]
Bonjour,

Je rencontre des difficultés à faire fonctionner py-qgis-wps.
J’ai installé py-qgis-wps depuis une image Docker (qgis-wps:ltr-rc).

J'ai suivi les instructions présentes sur Docker-hub :
`docker network create network_py_qgis_wps`
`docker run -d --rm --name redis --net network_py_qgis_wps redis:4`

`docker run -it --rm -p 127.0.0.1:8080:8080 --net network_py_qgis_wps -v '/home/administrateur/py-qgis-wps/processing':/processing -v '/home/administrateur/py-qgis-wps/projects':/projects -v '/home/administrateur/py-qgis-wps/outputs':/srv/data -e QGSWPS_SERVER_WORKDIR=/srv/data -e QGSWPS_SERVER_PARALLELPROCESSES=2 -e QGSWPS_SERVER_LOGSTORAGE=REDIS -e QGSWPS_PROCESSSING_PROVIDERS=provider1,provider2 -e QGSWPS_PROCESSSING_PROVIDERS_MODULE_PATH=/processing -e QGSWPS_CACHE_ROOTDIR=/projects -e QGSWPS_USER=1000:1000 3liz/qgis-wps:ltr-rc`

Sur 172.18.0.3:8080/ j’obtiens un fichier JSON avec des informations sur py-qgis-wps. (la même chose s’affiche sur 127.0.0.1:8080/)
Lorsque je me rends sur http://172.18.0.3:8080/ows/?service=WPS&request=GetCapabilities, j’obtiens bien un xml des métadonnées.

Dans mon dossier /home/administrateur/py-qgis-wps/processing, j’ai un traitement appelé ‘ExampleProcessingAlgorithm’ (ExampleProcessingAlgorithm.py)

Dans __init__.py, j’ai inséré les lignes suivantes :
```
def WPSClassFactory(iface: WPSServerInterface) -> Any:

    from ExampleProcessingAlgorithm import ExampleProcessingAlgorithm

    iface.registerProvider( ExampleProcessingAlgorithm() )
```

Cependant, lorsque je lance une requête _DescribeProcess_ ou _Execute_ : _http://172.18.0.3:8080/ows/?service=WPS&version=1.0.0&request=Execute&Identifier=ExampleProcessingAlgorithm_, j’obtiens un xml contenant « Unknown process ''ExampleProcessingAlgorithm'' ».

127.0.0.1:8080/ui me renvoit une erreur 404.

Je n'arrive pas à trouver ce à côté de quoi je passe.

Merci d'avance pour l'aide que vous pourrez me fournir !

**Comment by dmarteau** [comment]
L'identifiant du processus n'est pas correcte: il doit être de la forme `<provider>:<algorithm>`

Faite d'abord une requête `GetCapabilities` qui vous montrera les processus disponibles, vous pourrez tester si votre algorithme est correctement chargé.

D'autre part je vous recommande d'utiliser `docker-compose` (un exemple ici: https://github.com/3liz/py-qgis-wps/blob/master/docker/docker-compose.yml) pour executer les applications Docker: c'est plus facile a maintenir que la ligne de commande.

**Comment by Gustry** [comment]
N'ayant pas accès au code, on ne peut pas savoir, mais j'ai l'impression que le code Python n'est pas bon : 

```python
    from ExampleProcessingAlgorithm import ExampleProcessingAlgorithm
    iface.registerProvider( ExampleProcessingAlgorithm() )  # pas bon ici
```

Il faut ajouter un `QgsProcessingProvider` au `registerProvider` et non pas un `QgsProcessingAlgorithm`.

**Comment by mgaudin** [comment]
Bonjour,

Merci beaucoup pour vos réponses.

@dmarteau, j'ai repris le dossier le contenu du dossier https://github.com/3liz/py-qgis-wps/tree/master/docker en adaptant le contenu du fichier `docker-compose.yml` à ma configuration : 

```
version: '3'
services:
  wps:
    image: 3liz/qgis-wps:ltr-rc
    environment:
      QGSWPS_SERVER_PARALLELPROCESSES: '2'
      QGSWPS_SERVER_LOGSTORAGE: REDIS
      QGSWPS_REDIS_HOST: redis
      QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH: /processing
      QGSWPS_CACHE_ROOTDIR: /projects
      QGSWPS_SERVER_WORKDIR: /srv/data
      QGSWPS_USER: 1000:1000
      QGSWPS_LOGLEVEL: DEBUG
    volumes:
      - /home/administrateur/py-qgis-wps/processing:/processing
      - /home/administrateur/py-qgis-wps/projects:/projects
      - /home/administrateur/py-qgis-wps/outputs:/srv/data
      - /home/qgis:/home/qgis
    ports:
      - 127.0.0.1:8888:8080
  redis:
      image: redis:5-alpine
```

@Gustry effectivement c'était une erreur de ma part.
J'ai un fichier `exemple_algo_provider.py` contenant une classe `ExempleAlgoeProvider(QgsProcessingProvider)` et un fichier `exemple_algo_algorithm.py` contenant une classe `ExempleAlgoeAlgorithm(QgsProcessingAlgorithm)`.
Dans le fichier `__init__.py`, j'ai désormais le code suivant :

```python
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExempleAlgoe class from file ExempleAlgoe.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .exemple_algo import ExempleAlgoePlugin
    return ExempleAlgoePlugin()
    

    
def WPSClassFactory(iface: WPSServerInterface) -> Any:
    #
    from .exemple_algo_provider import ExempleAlgoeProvider

    iface.registerProvider(ExempleAlgoeProvider())
```

J'ai donc lancé la commande `docker-compose up`.

J'ai lancé une requête `GetCapabilities`. La balise `ProcessOfferings` est vide, ce qui me laisse penser que mon algorithme n'est pas chargé.

Dans `/home/administrateur/py-qgis-wps/processing`, j'ai bien mes éléments :
- `__init__.py`
- `exemple_algo.py`
- `exemple_algo_provider.py`
- `exemple_algo_algorithm.py`
- `metadata.txt`

Cependant, le processus n'est pas chargé et n'est pas reconnu à l'exécution de la requête `GetCapabilities`.

Merci encore d'avance pour l'aide que vous pourrez me fournir !

**Comment by akudekar** [comment]
I am having the exact same issue. Any updates here?

**Comment by dmarteau** [comment]
> J'ai lancé une requête GetCapabilities. La balise ProcessOfferings est vide, ce qui me laisse penser que mon algorithme n'est pas chargé.

Please, have a look to the logs and, loaded providers are printed. Eventually use debug mode to get more insights.

**Comment by akudekar** [comment]
I can see that "script" and "model" are the only providers enabled even though I have specified the Processing algorithm volume in docker-compose. I am trying to get basic qgis processing algs like buffer and clip to work on Lizmap frontend. I am sure there are more than one errors here and I appreciate any help I can get

```
Attaching to docker_wps_1, docker_redis_1
redis_1  | 1:C 08 Jul 2021 12:55:18.556 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 08 Jul 2021 12:55:18.556 # Redis version=5.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 08 Jul 2021 12:55:18.556 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 08 Jul 2021 12:55:18.557 * Running mode=standalone, port=6379.
redis_1  | 1:M 08 Jul 2021 12:55:18.557 # Server initialized.

redis_1  | 1:M 08 Jul 2021 12:55:18.557 * Ready to accept connections

wps_1    | Checking for legacy environment
wps_1    | Checking for legacy environment
wps_1    | wpsserver 1.6.2 (build 202105210837,commit 696dd32)
wps_1    | loading configuration
wps_1    | Log level set to DEBUG
wps_1    | 
wps_1    | 2021-07-08 12:55:19,057	[1]	INFO	Running WPS server on port 0.0.0.0:8080
wps_1    | 2021-07-08 12:55:19,057	[1]	DEBUG	Looking for plugins in /usr/share/qgis_wps/processing
wps_1    | 2021-07-08 12:55:19,057	[1]	WARNING	No WPS plugin found in /usr/share/qgis_wps/processing

wps_1    | 2021-07-08 12:55:19,057	[1]	DEBUG	Looking for plugins in /processing/algs
wps_1    | 2021-07-08 12:55:19,074	[1]	WARNING	No WPS plugin found in /processing/algs
wps_1    | 2021-07-08 12:55:19,075	[1]	DEBUG	LOGSTORE: Initializing REDIS session
wps_1    | 2021-07-08 12:55:19,077	[20]	INFO	Starting worker pool
wps_1    | 2021-07-08 12:55:19,079	[1]	DEBUG	Started server
wps_1    | 2021-07-08 12:55:19,079	[23]	DEBUG	Connecting to ipc:///tmp/qgswps/pooladdr_1
wps_1    | 2021-07-08 12:55:19,080	[24]	DEBUG	Connecting to ipc:///tmp/qgswps/pooladdr_1
wps_1    | 2021-07-08 12:55:19,080	[23]	DEBUG	Identity set to b'\xbf\xa9\x90z\xdf\xeb\x11\xeb\xab\xa3\x02B\xac\x1c\x00\x03'
wps_1    | 2021-07-08 12:55:19,080	[1]	DEBUG	Installing processes
wps_1    | 2021-07-08 12:55:19,080	[23]	DEBUG	Enabling broadcast notification
wps_1    | 2021-07-08 12:55:19,081	[1]	DEBUG	*** Folder settings: Processing/Configuration/SCRIPTS_FOLDERS = /processing/algs/scripts
wps_1    | 2021-07-08 12:55:19,081	[24]	DEBUG	Identity set to b'\xbf\xa9\xb0\x82\xdf\xeb\x11\xeb\xae>\x02B\xac\x1c\x00\x03'
wps_1    | 2021-07-08 12:55:19,081	[24]	DEBUG	Enabling broadcast notification
wps_1    | 2021-07-08 12:55:19,081	[23]	DEBUG	*** Folder settings: Processing/Configuration/SCRIPTS_FOLDERS = /processing/algs/scripts
wps_1    | 2021-07-08 12:55:19,082	[1]	DEBUG	*** Folder settings: Processing/Configuration/MODELS_FOLDER = /processing/algs/models
wps_1    | 2021-07-08 12:55:19,082	[24]	DEBUG	*** Folder settings: Processing/Configuration/SCRIPTS_FOLDERS = /processing/algs/scripts
wps_1    | 2021-07-08 12:55:19,082	[23]	DEBUG	*** Folder settings: Processing/Configuration/MODELS_FOLDER = /processing/algs/models
wps_1    | 2021-07-08 12:55:19,082	[24]	DEBUG	*** Folder settings: Processing/Configuration/MODELS_FOLDER = /processing/algs/models
wps_1    | 2021-07-08 12:55:19,326	[1]	INFO	Starting Qgis application: 3.18.1-Z�rich
wps_1    | 2021-07-08 12:55:19,326	[1]	INFO	Setting offscreen mode
wps_1    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'

wps_1    | 2021-07-08 12:55:19,356	[24]	INFO	Starting Qgis application: 3.18.1-Z�rich
wps_1    | 2021-07-08 12:55:19,357	[24]	INFO	Setting offscreen mode
wps_1    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
wps_1    | 2021-07-08 12:55:19,358	[23]	INFO	Starting Qgis application: 3.18.1-Z�rich
wps_1    | 2021-07-08 12:55:19,358	[23]	INFO	Setting offscreen mode
wps_1    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
wps_1    | 2021-07-08 12:55:19,473	[1]	INFO	[qgis:1] Installing cleanup hook
wps_1    | 2021-07-08 12:55:19,473	[1]	INFO	[qgis:1] Qgis application initialized......
wps_1    | 2021-07-08 12:55:19,500	[24]	INFO	[qgis:24] Installing cleanup hook
wps_1    | 2021-07-08 12:55:19,500	[24]	INFO	[qgis:24] Qgis application initialized......
wps_1    | 2021-07-08 12:55:19,503	[23]	INFO	[qgis:23] Installing cleanup hook
wps_1    | 2021-07-08 12:55:19,504	[23]	INFO	[qgis:23] Qgis application initialized......
wps_1    | /usr/lib/python3/dist-packages/osgeo/__init__.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
wps_1    |   import imp

wps_1    | 2021-07-08 12:55:19,789	[1]	ERROR	[qgis:1] Processing: Problem with GRASS installation: GRASS was not found or is not correctly installed
wps_1    | 2021-07-08 12:55:19,806	[1]	ERROR	[qgis:1] Processing: Problem with SAGA installation: SAGA was not found or is not correctly installed
wps_1    | /usr/lib/python3/dist-packages/osgeo/__init__.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
wps_1    |   import imp
wps_1    | 2021-07-08 12:55:19,809	[24]	ERROR	[qgis:24] Processing: Problem with GRASS installation: GRASS was not found or is not correctly installed
wps_1    | 2021-07-08 12:55:19,811	[1]	INFO	[qgis:1] QGis processing initialized
wps_1    | 2021-07-08 12:55:19,812	[1]	DEBUG	= Registering provider 'script'
wps_1    | 2021-07-08 12:55:19,812	[1]	DEBUG	= Registering provider 'model'
wps_1    | 2021-07-08 12:55:19,818	[1]	DEBUG	Registering factory: @3liz.org/cache/protocol-handler;1?scheme=file
wps_1    | 2021-07-08 12:55:19,819	[1]	DEBUG	Registering factory: @3liz.org/cache/protocol-handler;1?scheme=postgres

wps_1    | 2021-07-08 12:55:19,819	[1]	DEBUG	Registering factory: @3liz.org/cache-manager;1
wps_1    | /usr/lib/python3/dist-packages/osgeo/__init__.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
wps_1    |   import imp
wps_1    | 2021-07-08 12:55:19,822	[23]	ERROR	[qgis:23] Processing: Problem with GRASS installation: GRASS was not found or is not correctly installed
wps_1    | 2021-07-08 12:55:19,824	[24]	ERROR	[qgis:24] Processing: Problem with SAGA installation: SAGA was not found or is not correctly installed
wps_1    | 2021-07-08 12:55:19,826	[1]	DEBUG	Loading processing algorithms from provider 'script'
wps_1    | 2021-07-08 12:55:19,826	[1]	DEBUG	Loading processing algorithms from provider 'model'
wps_1    | 2021-07-08 12:55:19,827	[1]	WARNING	No published processes !
wps_1    | 2021-07-08 12:55:19,828	[1]	INFO	Loading module: qgssrv_contrib_access_policy:lizmapaccesspolicy

wps_1    | 2021-07-08 12:55:19,830	[24]	INFO	[qgis:24] QGis processing initialized
wps_1    | 2021-07-08 12:55:19,830	[24]	DEBUG	= Registering provider 'script'
wps_1    | 2021-07-08 12:55:19,830	[24]	DEBUG	= Registering provider 'model'
wps_1    | 2021-07-08 12:55:19,830	[24]	DEBUG	Starting ZMQ worker loop
wps_1    | 2021-07-08 12:55:19,839	[23]	ERROR	[qgis:23] Processing: Problem with SAGA installation: SAGA was not found or is not correctly installed
wps_1    | 2021-07-08 12:55:19,843	[1]	INFO	Starting supervisor
wps_1    | 2021-07-08 12:55:19,843	[1]	INFO	WPS Server ready
wps_1    | 2021-07-08 12:55:19,843	[1]	DEBUG	WORKER READY b'\xbf\xa9\xb0\x82\xdf\xeb\x11\xeb\xae>\x02B\xac\x1c\x00\x03'
wps_1    | 2021-07-08 12:55:19,845	[23]	INFO	[qgis:23] QGis processing initialized
wps_1    | 2021-07-08 12:55:19,845	[23]	DEBUG	= Registering provider 'script'
wps_1    | 2021-07-08 12:55:19,845	[23]	DEBUG	= Registering provider 'model'
wps_1    | 2021-07-08 12:55:19,845	[23]	DEBUG	Starting ZMQ worker loop

wps_1    | 2021-07-08 12:55:19,846	[1]	DEBUG	WORKER READY b'\xbf\xa9\x90z\xdf\xeb\x11\xeb\xab\xa3\x02B\xac\x1c\x00\x03'

wps_1    | 2021-07-08 12:57:19,326	[1]	DEBUG	Request: getcapabilities

wps_1    | 2021-07-08 12:57:19,327	[1]	DEBUG	Serializing XML response
wps_1    | 2021-07-08 12:57:19,327	[1]	REQ	172.28.0.1	200	GET	/ows/?SERVICE=WPS&request=GetCapabilities&version=1.0.0	2	2893	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0	

```
This is my docker file:
I am not sure if specifying the path to the qgis processing plugin works. I have edited the ```metadata.txt``` and ```__init__.py``` files according to the documentation 
```
version: '3'
services:
  wps:
    image: 3liz/qgis-wps:3.18
    environment:
      QGSWPS_SERVER_PARALLELPROCESSES: '2'
      QGSWPS_SERVER_LOGSTORAGE: REDIS
      QGSWPS_REDIS_HOST: redis
      QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH: /processing
      QGSWPS_CACHE_ROOTDIR: /projects
      QGSWPS_SERVER_WORKDIR: /srv/data
      QGSWPS_USER: 1000:1000
      QGSWPS_LOGLEVEL: DEBUG
    volumes:
      - D:\QGIS\apps\qgis-ltr\python\plugins\processing:/processing
      - E:\Thesis\lizmap\lizmap-docker-compose\lizmap\instances\:/projects
      - E:\Thesis\lizmap\lizmap-docker-compose\lizmap\instances\:/srv/data
      - ${PWD}/.home:/home/qgis
    ports:
      - 127.0.0.1:8888:8080
  redis:
      image: redis:5-alpine
```

**Comment by dmarteau** [comment]
> I can see that "script" and "model" are the only providers enabled

Only script models and providers located in `QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH` are published by default. This is by design since the use case is to publish only specific designed modules - but this does not prevent to use internal qgis providers in your own algorithms - which is the recommended way, since usually you do not want to expose the full set of qgis algorithms.

If you want to specify other internal providers - which is not recommended - you must pass the explicit list of providers in `QGSWPS_PROCESSING_EXPOSED_PROVIDERS`

**Comment by akudekar** [comment]
> 
> 
> > I can see that "script" and "model" are the only providers enabled
> 
> Only script models and providers located in `QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH` are published by default. This is by design since the use case is to publish only specific designed modules - but this does not prevent to use internal qgis providers in your own algorithms - which is the recommended way, since usually you do not want to expose the full set of qgis algorithms.
> 
> If you want to specify other internal providers - which is not recommended - you must pass the explicit list of providers in `QGSWPS_PROCESSING_EXPOSED_PROVIDERS`

Thanks for the clarification. Can I suggest a few updates to the documentation so that its a bit easier to understand the procedure better?

**Comment by mgaudin** [comment]
Hello,

Thank you for the answers.

I solved my issue inserting my script in a subfolder of my "processing" folder.

![py-qgis-wps](https://user-images.githubusercontent.com/26749791/125055525-93dfa580-e0a7-11eb-9393-962be7f9ab59.png)

The processing is now loaded.

**Comment by dmarteau** [comment]
Yes, processing providers are python packages, they must be deployed as such.

**Comment by cBevilaqua** [comment]
can someone share a metadata.txt example please? Thanks.
