### ISSUE TITLE
Cannot set different port for docker instance

### ISSUE THREAD

**Issue by patrickkaleta** [3liz/py-qgis-wps#26]
I'm trying to setup both the [py-qgis-server](https://github.com/3liz/py-qgis-server) and [py-qgis-wps](https://github.com/3liz/py-qgis-wps) on one server using Docker (as described in your docs). Since both use by default the 8080 port, I tried to change the port for th py-qgis-wps instance like this:
```
docker run -it --rm -p 8081:8081 --net mynet \
       -v /path/to/processing/:/processing \
       -v /path/to/qgis/projects:/projects \
       -v /path/to/processing/output/dir:/srv/data \
       -e QGSWPS_SERVER_HTTP_PORT=8081 \
       ... other environment variables ...    
       3liz/qgis-wps:3.22
```

However, I'm unable to call `http://my-server-ip:8081/ows/?SERVICE=WPS&VERSION=1.1.0&REQUEST=GetCapabilities `

Running the docker instance with the default 8080 port works just fine. I'm also able to alter the port for the [py-qgis-server](https://github.com/3liz/py-qgis-server) using above command. So, am I missing something here or could this be a bug in py-qgis-wps?

**Comment by dmarteau** [comment]
Your command is wrong: use `-p 8081:8080` (map internal port 8080 to host port 8081)

**Comment by patrickkaleta** [comment]
Of course...  thanks, now working as expected!
