### ISSUE TITLE
VERSION file is missing

### ISSUE THREAD

**Issue by ptitjano** [3liz/py-qgis-wps#33]
The `setup.py` file tries to open a `VERSION` file (`get_version()` function) but this file does not exist.

**Comment by Gustry** [comment]
Did you download the zip file provided by GitHub ? Or did you git clone ?

If yes :
Either you should use a package from PyPi : https://pypi.org/project/py-qgis-wps/
Or you need to use the Makefile provided : `make manifest` : https://github.com/3liz/py-qgis-wps/blob/master/Makefile#L28
Or you can download the tar package from the release page https://github.com/3liz/py-qgis-wps/releases/tag/1.8.4

I'm closing as I think it's only this, feel free to comment anyway.

**Comment by dmarteau** [comment]
Use the Makefile to build the package: `make build`

**Comment by ptitjano** [comment]
Thanks for your responses. I tried to follow the `README.md` and this part : https://github.com/3liz/py-qgis-wps#from-source

My workflow:

```
git clone git@github.com:3liz/py-qgis-wps.git
python3 -m venv venv
source venv/bin/activate
pip install -e .
```

Which resulted in: 

```
pip install -e .
Obtaining file:///home/jean/dev/py-qgis-wps
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jean/dev/py-qgis-wps/setup.py", line 19, in <module>
          VERSION = get_version()
                    ^^^^^^^^^^^^^
        File "/home/jean/dev/py-qgis-wps/setup.py", line 15, in get_version
          with open('VERSION') as fp:
               ^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I understand your comments correctly, I think that the `README.md` should mention the appropriate `make` command
