### ISSUE TITLE
Exposing Processing algorithms with py-qgis-wps and docker-compose

### ISSUE THREAD

**Issue by maborroto** [3liz/py-qgis-wps#36]
Hello,
I'm trying to expose the processing algorithms with **py-qgis-wps** to be used with Lizmap. I'm using the docker-compose variant because it is easy to install and use. Everything went well until I decided to expose the **"native"** algorithms.
 In the docker-compose.yml file, I set the provider property in this way:  
`QGSWPS_PROCESSING_EXPOSED_PROVIDERS: native,qgis`

When executing **docker compose up** I'm getting the error reported below: 
![image](https://user-images.githubusercontent.com/24281087/228886546-de884321-ccb1-481a-bc96-874604b1b87f.png)

This error occurs just when using the **"native"** provider; if I use just the  **qgis** (**QGSWPS_PROCESSING_EXPOSED_PROVIDERS:** qgis) provider, everything works well but I can't see the **"native"** algorithms, e.g. `native:buffer`

PD: I'm using the docker image: **3liz/qgis-wps:3.30**, but I also used **3liz/qgis-wps:release-rc** and **3liz/qgis-wps:ltr-rc**, but i got the same error.

Can you give me some hints on how to solve this problem?

Thanks!!

**Comment by dmarteau** [comment]
The answer is simple: you cannot expose the `native` provider .   

Neither you should  expose the `qgis` provider: theses algorithms have never been designed to work with WPS marshalling (remember that the input/output parameter's set in Qgis processing is much larger that what's possible to expose in WPS). 

*But* you may wrap call to native/qgis algorithm into your own algorithm to fit specialized needs, which is more suited to be used as WPS service.

**Comment by maborroto** [comment]
I got it, thank you a lot.  I have written a custom algorithm wrapping the `native:buffer`, and it works perfectly.

**Comment by dmarteau** [comment]
:+1:

**Comment by cBevilaqua** [comment]
> I got it, thank you a lot. I have written a custom algorithm wrapping the `native:buffer`, and it works perfectly.

@maborroto , can you please send me the wrapper you made with the buffer algorithm? I need to do the same but have no idea how to do it. Thanks.

**Comment by Gustry** [comment]
If I were you, I would go for a processing model, easier as it seems you are not familiar with PyQGIS (which is what the wrapper is about)

* https://docs.qgis.org/latest/en/docs/user_manual/processing/scripts.html
* https://docs.qgis.org/latest/en/docs/pyqgis_developer_cookbook/processing.html

@cBevilaqua In your processing toolbox, you have a Python button at the top, "Create script from template" which is doing the wrapper more or less with the example provided.

**Comment by cBevilaqua** [comment]
> If I were you, I would go for a processing model, easier as it seems you are not familiar with PyQGIS (which is what the wrapper is about)
> 
> * https://docs.qgis.org/latest/en/docs/user_manual/processing/scripts.html
> * https://docs.qgis.org/latest/en/docs/pyqgis_developer_cookbook/processing.html
> 
> @cBevilaqua In your processing toolbox, you have a Python button at the top, "Create script from template" which is doing the wrapper more or less with the example provided.

Thanks!

I made a small example here: https://github.com/cBevilaqua/qgis-sample-processing, following the example here (https://docs.qgis.org/3.28/en/docs/user_manual/processing/scripts.html) and got it working.
Thanks!
