### ISSUE TITLE
Question: expiration time

### ISSUE THREAD

**Issue by IceflowRE** [3liz/py-qgis-wps#45]
The expire time is configurable in seconds, is it still possible (without huge side effects) to choose an expiration time of several days or a week?

**Comment by dmarteau** [comment]
This number in compared with a floating point timestamp as returned by the datetime module. A week is 604800 seconds, so you really don't need to worry about side effects.

**Comment by IceflowRE** [comment]
> This number in compared with a floating point timestamp as returned by the datetime module. A week is 604800 seconds, so you really don't need to worry about side effects.

Ok thanks! I was worried about some internals, which might not expect so high second numbers.
