### ISSUE TITLE
use of default value in a request

### ISSUE THREAD

**Issue by ptitjano** [3liz/py-qgis-wps#57]
As a test I have created this simple process with QGIS. It computes the buffer of a vector layer: 

![Capture d’écran du 2024-05-24 16-42-08](https://github.com/3liz/py-qgis-wps/assets/497207/74e7bfae-7b16-419d-b8c8-20819cd08a76)

The "number_of_segments" has a default value equal to 5.

I can run this process with the following xml: 

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" service="WPS" version="1.0.0">
  <ows:Identifier>model:buffer_simple</ows:Identifier>
  <wps:DataInputs>
    <wps:Input>
      <ows:Identifier>input_layer</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>/home/foo/data.shp</wps:LiteralData>
      </wps:Data>
    </wps:Input>
    <wps:Input>
      <ows:Identifier>number_of_segments</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>6</wps:LiteralData>
      </wps:Data>
    </wps:Input>
    <wps:Input>
      <ows:Identifier>buffer_layer</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>buffer_layer</wps:LiteralData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
</wps:Execute>
```

It works. However, "number_of_segments" has a default value. So, I would expect the default value to be used if the parameter is missing in the xml request: 

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" service="WPS" version="1.0.0">
  <ows:Identifier>model:buffer_simple</ows:Identifier>
  <wps:DataInputs>
    <wps:Input>
      <ows:Identifier>input_layer</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>/home/foo/data.shp</wps:LiteralData>
      </wps:Data>
    </wps:Input>
    <wps:Input>
      <ows:Identifier>buffer_layer</ows:Identifier>
      <wps:Data>
        <wps:LiteralData>buffer_layer</wps:LiteralData>
      </wps:Data>
    </wps:Input>
  </wps:DataInputs>
</wps:Execute>
```

However, it fails with the following error because "number_of_segments" is missing. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- py-qgis-wps 1.8.7rc0 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
  <ows:Exception exceptionCode="MissingParameterValue" locator="number_of_segments" >
      <ows:ExceptionText>number_of_segments</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

I would have expected the default value (5) to be used in that case. Is it the expected behavior?

Thanks.

**Comment by dmarteau** [comment]
>  Is it the expected behavior?

As a matter of fact yes: since the the parameter is not 'optional' it is required as WPS input; the default value is given in the process description (as prescribed in WPS spec) for the client to set a default input value.

If you want to be able to omit the input in the request you must create a Qgis parameter with 'optional=True' : in this case the description of the input will show a  'minOccurs' of 0, which indicates that the input may be omitted from the execute request.

**Comment by ptitjano** [comment]
Thanks for the explanation. This makes perfect sense.
