### ISSUE TITLE
Removal of docker image 3.38

### ISSUE THREAD

**Issue by IceflowRE** [3liz/py-qgis-wps#59]
In DockerHub the version 3.38 was removed. Is there any reason?

**Comment by Gustry** [comment]
3.38 is already EOL by the QGIS roadmap and it wasn't LTR, so it shouldn't be used anyway today, better to use 3.40.0

If it has been removed manually, I guess it's because of a bug in the QGIS server part. (https://github.com/qgis/QGIS/pull/58937)
