### ISSUE TITLE
Help string on a parameter in QGIS 3.16

### ISSUE THREAD

**Issue by Gustry** [3liz/py-qgis-wps#8]
The new help string has been merged in QGIS 3.16.

In `QgsProcessingParameter`, there is now a `help()` and `setHelp()`.

![Selection_016](https://user-images.githubusercontent.com/1609292/92464062-ee308100-f1cc-11ea-8365-7089777b90e9.png)

**Comment by dmarteau** [comment]
Good to know !

**Comment by dmarteau** [comment]
@Gustry How do you suggests to use it in WPS ? There is already an 'abstract' WPS field which is filled with the `description` value for the linked `QgsProcessingParameter`.

**Comment by rldhont** [comment]
@dmarteau it could be like that:
* `name` is the `identifier`
* `description` is the `title`
* `helpstring` is the `abstract`

**Comment by dmarteau** [comment]
> name is the identifier

Which is actually the case

> description is the title

That's may be not appropriate as long as the "Title" is supposed to be a human readable label for the name of the parameter (as displayed by the client and must be limited in its length.

**Comment by rldhont** [comment]
the `description` is used in QGIS UI as the `title` in WPS.

**Comment by dmarteau** [comment]
> The description is used in QGIS UI as the title in WPS.

Ok, so we may stick to the same usage.....

**Comment by dmarteau** [comment]
This will be available as soon as Qgis 3.16 is the next `release` version (atm the  `release` version is 3.14)

**Comment by dmarteau** [comment]
Fixed in 312ab0d940b6e9238180cba272be44bc26da0cf0
