### ISSUE TITLE
QgsProcessingParameterVectorDestination TypeVector only WFS output

### ISSUE THREAD

**Issue by rldhont** [3liz/py-qgis-wps#9]
If the type of a `QgsProcessingParameterVectorDestination` is set to `QgsProcessing.TypeVector` the algorithm will return a table (with or without geometry). When this type used for a sink this indicates the sink has no geometry.

If the type `QgsProcessing.TypeVector` is defined the corresponding WPS output has not to be a WMS one.

It is the same for `QgsProcessingOutputVectorLayer`

**Comment by dmarteau** [comment]
> If the type QgsProcessing.TypeVector is defined the corresponding WPS output has not to be a WMS one.

What should be the returned mime type ?

**Comment by rldhont** [comment]
The mime types are: `text/xml; subtype=gml/2.1.2`, `text/xml; subtype=gml/3.1.1`, and `application/vnd.geo+json`
